
"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://djangoproject.com

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-s4!9)&#f1prdv%r*1#)4662ci@cifv=*_%myhl6av^&%$wxx%i')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '.onrender.com,localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api', # Your app name
    'rest_framework.authtoken'
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # MUST BE FIRST
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication', # Optional
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# Password validation
# https://djangoproject.com

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://djangoproject.com

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://djangoproject.com

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 2. Media Files (User Uploads like Product Images)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 3. Database Configuration (Auto-switches to PostgreSQL on Render)
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{os.path.join(BASE_DIR, 'db.sqlite3')}",
        conn_max_age=600
    )
}

# Production HTTPS and Security Settings
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# CORS Configuration
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "https://el-mart.netlify.app", 
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "https://elmart-ni79.vercel.app",
    "https://elmart-six.vercel.app"
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "https://elmart.onrender.com",
    "https://elmart-ni79.vercel.app",
    "https://elmart-six.vercel.app",
    "https://el-mart.netlify.app",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "authorization", # Make sure this is here!
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Tell Django to use our custom user model
AUTH_USER_MODEL = 'api.User'

# ── El-Mart business rules ──────────────────────────────────────────────
# % of every order's value El-Mart keeps as commission; the rest settles
# straight to the seller's own bank account via their Paystack subaccount.
PLATFORM_COMMISSION_PERCENT = 7

# Featured-listing ("boost") pricing — 100% platform revenue.
FEATURE_BOOST_PRICES = {
    7: 2000,    # 7 days for ₦2,000
    30: 6000,   # 30 days for ₦6,000
}

# ── Logistics (Terminal Africa) ─────────────────────────────────────────
TERMINAL_API_KEY = os.environ.get('TERMINAL_API_KEY', '')
# El-Mart's default packaging ID on Terminal's platform — get this from your
# Terminal dashboard/Postman collection (Packaging endpoints) after signing up.
TERMINAL_DEFAULT_PACKAGING_ID = os.environ.get('TERMINAL_DEFAULT_PACKAGING_ID', '')
# % markup added on top of Terminal's real delivery cost — this is El-Mart's
# delivery-fee revenue line from the handbook.
DELIVERY_MARKUP_PERCENT = 12

